name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Clasp
        run: npm install -g @google/clasp@latest

      - name: Create client_secret.json
        run: echo "${{ secrets.CLASP_CREDENTIALS }}" | base64 -d > client_secret.json

      - name: Login with OAuth
        run: clasp login --creds client_secret.json --no-localhost

      - name: Push to GAS
        run: clasp push -f
