name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g @google/clasp

      - name: Restore .clasprc.json
        run: echo "$CLASP_CREDENTIALS" | tr -d '\r' | base64 -d > "$HOME/.clasprc.json"

      - name: Push to Google Apps Script
        run: clasp push -f
