name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main
  workflow_dispatch:   # 手動実行も可能に

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g @google/clasp

      - name: Authenticate with Google
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC_JSON" | base64 -d > $HOME/.clasprc.json
          echo "=== ~/.clasprc.json ==="
          cat $HOME/.clasprc.json
          # パーミッションを明示的に設定
          chmod 600 $HOME/.clasprc.json

      - name: Push to Google Apps Script
        run: clasp push -f
