name: Deploy to Google Apps Script

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore .clasprc.json (from secret)
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
        run: |
          mkdir -p "$HOME"
          echo "$CLASP_CREDENTIALS" | tr -d '\r' | base64 -d > "$HOME/.clasprc.json"
          echo "✅ Restored ~/.clasprc.json"
          head -c 120 "$HOME/.clasprc.json" || true
          echo

      - name: Ensure .clasp.json exists (scriptId)
        run: |
          if [ ! -f ".clasp.json" ]; then
            echo "❌ .clasp.json not found at repo root"; exit 1
          fi
          echo "📄 .clasp.json:" && cat .clasp.json

      - name: Push to Google Apps Script
        run: clasp push -f
