name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g @google/clasp

      - name: Setup clasp auth
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC_JSON" | base64 -d > $HOME/.clasprc.json
          echo "=== ~/.clasprc.json ==="
          cat $HOME/.clasprc.json
          ls -la $HOME

      - name: Push to Google Apps Script
        run: clasp push -f
