name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Clasp
        run: npm install -g @google/clasp@latest

      # GitHub Secret から OAuth 認証ファイルを生成
      - name: Create .clasprc.json
        run: echo "${{ secrets.CLASP_CREDENTIALS }}" | base64 -d > ~/.clasprc.json

      # clasp push 実行
      - name: Push to GAS
        run: clasp push -f
