name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Clasp
        run: npm install -g @google/clasp@latest

      - name: Decode service account key
        run: echo "${{ secrets.CLASP_CREDENTIALS }}" | base64 -d > ./sa.json

      - name: Authenticate clasp with service account
        run: clasp login --creds ./sa.json

      - name: Push to GAS
        run: clasp push -f
