name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # Node.js セットアップ
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # clasp インストール
      - run: npm install -g @google/clasp

      # Google 認証
      - name: Authenticate with Google
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC_JSON" | base64 -d > ~/.clasprc.json
          echo "=== ~/.clasprc.json ==="
          cat ~/.clasprc.json

      # デプロイ
      - name: Push to Google Apps Script
        run: clasp push -f
