name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create .clasprc.json
        run: |
          echo '${{ secrets.CLASP_CREDENTIALS }}' > ~/.clasprc.json

      - name: Push to GAS
        run: |
          clasp push --force
