name: Deploy to Google Apps Script

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore .clasprc.json
        env:
          CLASP_RC_JSON_B64: ${{ secrets.CLASP_RC_JSON_B64 }}
        run: |
          mkdir -p "$HOME"
          echo "$CLASP_RC_JSON_B64" | tr -d '\r' | base64 -d > "$HOME/.clasprc.json"
          echo "✅ .clasprc.json restored"
          cat "$HOME/.clasprc.json" | head -c 200 || true

      - name: Ensure .clasp.json exists
        run: |
          if [ ! -f ".clasp.json" ]; then
            echo "❌ .clasp.json not found in repo root"
            exit 1
          fi
          cat .clasp.json

      - name: Deploy
        run: clasp push -f
