name: Deploy to Google Apps Script

on:
  pull_request:
    types: [closed]
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    # PR がマージされたとき or 手動実行のみ走る
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      # Secrets.CLASP_CREDENTIALS を ~/.clasprc.json に“正規化して”書き出す
      # （tokens.default 形式でも token 形式でもOKにする）
      - name: Setup clasp auth
        env:
          CREDS: ${{ secrets.CLASP_CREDENTIALS }}
        run: |
          node - <<'JS'
          const fs = require('fs');
          const path = require('path');
          const os = require('os');

          const raw = process.env.CREDS;
          if (!raw) { console.error('Missing CLASP_CREDENTIALS secret'); process.exit(1); }

          let src;
          try { src = JSON.parse(raw); }
          catch (e) { console.error('CLASP_CREDENTIALS is not valid JSON'); process.exit(1); }

          let out = src;
          // GitHub Secret が { tokens: { default: {...} } } の場合は .clasprc.json 形式に変換
          if (src.tokens && src.tokens.default) {
            const d = src.tokens.default;
            out = {
              token: {
                access_token: d.access_token || '',
                refresh_token: d.refresh_token,
                scope: d.scope || 'https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/script.container.ui',
                token_type: 'Bearer',
                expiry_date: Date.now() + 3600 * 1000
              },
              oauth2ClientSettings: {
                clientId: d.client_id,
                clientSecret: d.client_secret,
                redirectUri: 'http://localhost'
              },
              isLocalCreds: true
            };
          }

          const dest = path.join(os.homedir(), '.clasprc.json');
          fs.writeFileSync(dest, JSON.stringify(out));
          JS

      - name: Deploy (clasp push)
        run: npx clasp push --force
